version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf:delegated
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=certs@ethercreative.co.uk
    links:
      - node
      - postgres
    depends_on:
      - node
      - postgres
    restart: unless-stopped
  node:
    image: node:alpine
    command: >
      sh -c "${START_CMD}"
    volumes:
      - ./:/usr/src/app:delegated
    working_dir: /usr/src/app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    ports:
      - 3000:3000
    restart: unless-stopped
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data:delegated
    restart: unless-stopped
networks:
  default:
    external:
      name: proxy
